name: Deploy to WP Engine
description: Compiles CSS with Grunt, commits the changes, and then deploys to WP Engine.
inputs:
  wpengine-ssh-gateway-key-private:
    description: The private SSH key that you use to connect to the WPEngine SSH Gateway. You should pass this in from `secrets.WPE_SSHG_KEY_PRIVATE`.
    required: true
  environment-name:
    description: The name of your WP Engine install.
    required: true
  source-path:
    description: The source path to the theme you want to upload. Something like “wp-content/themes/genesis-child-theme”.
    required: true
  remote-path:
    description: The remote destination path of the theme you want to upload. Something like “wp-content/themes/genesis-child-theme”.
    required: true
  compile-with-grunt-and-commit:
    description: If true, builds the project with Grunt and commits the changes.
    required: true
    default: false
  rsync-flags:
    description: Command-line flags passed to rsync(1).
    required: true
    default: -azvr --inplace --delete --exclude=".*" --exclude-from=.deployignore
  cloudflare-purge-urls:
    description: A string containing a flow-style list (“'["https://a", "https://b"]'”) of URLs to purge from Cloudflare. If empty, this action will not be performed.
    required: false
  cloudflare-zone:
    description: The Cloudflare zone to purge URLs from. Frequently `secrets.CLOUDFLARE_ZONE`. This will need to be set for `cloudflare-purge-urls` to work.
    required: false
  cloudflare-token:
    description: The Cloudflare token used to purge URLs. Frequently `secrets.CLOUDFLARE_TOKEN`. This will need to be set for `cloudflare-purge-urls` to work.
    required: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3 # updated from v2
    - uses: actions/setup-node@v2
      with:
        node-version: 18 # updated from 17 (may be premature)

    - name: Compile with Grunt
      uses: elstudio/actions-js-build/build@v4
      if:   ${{ inputs.compile-with-grunt-and-commit == true }}

    - name: Commit changes
      uses: elstudio/actions-js-build/commit@v4
      if:   ${{ inputs.compile-with-grunt-and-commit == true }}
      with:
        commitMessage: Compile CSS

    - name: Deploy to WP Engine
      uses: wpengine/github-action-wpe-site-deploy@v3.0
      with:
        # OpenSSH private keys are multiple lines long and start with “---”.
        # `inputs` passing fails if we use the normal ${{ … }} expansion here. YAML literal style (“|”) fixes this.
        WPE_SSHG_KEY_PRIVATE: |
                              ${{ inputs.wpengine-ssh-gateway-key-private }}
        WPE_ENV:              ${{ inputs.environment-name }}
        SRC_PATH:             ${{ inputs.source-path }}
        REMOTE_PATH:          ${{ inputs.remote-path }}
        PHP_LINT:             true
        FLAGS:                ${{ inputs.rsync-flags }}
        CACHE_CLEAR:          true

    - name: Purge cache
      uses: jakejarvis/cloudflare-purge-action@master
      if:   ${{ join(inputs.cloudflare-purge-urls) != '' }}
      env:
        CLOUDFLARE_ZONE:  ${{ inputs.cloudflare-zone }}
        CLOUDFLARE_TOKEN: ${{ inputs.cloudflare-token }}
        PURGE_URLS:       ${{ inputs.cloudflare-purge-urls }}
